apiVersion: v1
kind: Service
metadata:
  name: the-road-to-react-book-service
spec:
  selector:
    app: the-road-to-react-book
  ports:
    - protocol: TCP
      port: 90
      targetPort: 5000
  type: LoadBalancer